# Generated by Django 5.2 on 2025-04-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_job_unaligned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='type',
            new_name='phylo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='unaligned_one_line',
        ),
        migrations.AlterField(
            model_name='job',
            name='unaligned',
            field=models.TextField(),
        ),
    ]
